version: '3.8'
services:
  ml:
    volumes:
    - ./src:/src/src
    - ./output:/src/output/
    build:
      context: .
    command: ["python", '/src/predict.py']
    image: gods_recognition
    env_file:
      - .env